### ISSUE TITLE
User story - Accessibility

### ISSUE THREAD

**Issue by KTC96** [KTC96/GrooveLocator#12]
### Story

As a **user with accessibility needs**, I can **easily access and use the website using a screen reader ** so that I can **use and enjoy the site**.

### Acceptance Criteria

- The application complies with WCAG accessibility standards.
- Screen readers can interpret all content and interactive elements.
- Keyboard navigation is supported for all interactive components.

### Tasks

- [ ] Test contrast using [WAVE](https://wave.webaim.org/) and [WebAIM](https://webaim.org/resources/contrastchecker/)
- [ ] Test using lighthouse developer tools
- [ ] Manually test with a screen reader
