### ISSUE TITLE
User story - Setup back-end and deploy

### ISSUE THREAD

**Issue by KTC96** [KTC96/GrooveLocator#3]
### Story

As a **developer**, I can **deploy my project to Heroku** so that I can **it is accessible to users on the internet**.

### Acceptance Criteria

- Initialize a Django project and create necessary project files and directories.
- Deploy the Django application to Heroku, ensuring it runs successfully on a live server.
- Verify that the deployed application works as expected on the Heroku domain.

### Tasks

- [x] Initialize a new Django project in GitPod.
- [x] Configure the Django project with required settings, including database, static files, and environment variables.
- [x] Add production environment database- Elephant SQL
- [x]  Deploy the Django application to Heroku, following the Heroku deployment guidelines and configuring environment variables as needed.
