### ISSUE TITLE
User story - CRUD functionality

### ISSUE THREAD

**Issue by KTC96** [KTC96/GrooveLocator#7]
### Story

As a **registered user**, I can **save events** so that I can **keep track of which events I want to attend**.

### Acceptance Criteria

- Registered users can click a "Save Event" button on event details. and saved events appear in the user's dashboard.
- User can edit and add details to the event, such as adding transport and hotel information
- Users can remove events from their dashboard.
### Tasks

- [ ] Design and add a "Save Event" button to the event details modal.
- [ ] Develop the mechanism to save events to the user's profile.
- [ ] Implement the ability to remove saved events from the user's dashboard.
