### ISSUE TITLE
User story - Email reminders

### ISSUE THREAD

**Issue by KTC96** [KTC96/GrooveLocator#8]
### Story

As a **user**, I can **receive notifications** so that I can **be reminded about upcoming events**.

### Acceptance Criteria

- Users receive email notifications for saved events a day before the event date.
- Notifications include event name, date, and venue information.
- Users can turn on or off these notifications in their profile settings.

### Tasks

- [ ] Develop a notification system for sending event reminders.
- [ ] Implement a user-friendly setting in the user profile for enabling/disabling notifications.
- [ ] Set up a scheduled job to send notifications a day before the event.
